@RestAPI_Image_HostAddress = https://localhost:7293

GET {{RestAPI_Image_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{RestAPI_Image_HostAddress}}/api/images
Content-Type: application/json

{
    "imageFile": (caminho/do/arquivo/imagem.jpg),
    "watermarkText": (string base64, opcional),
    "WatermarkImage": (caminho/do/arquivo/imagem.jpg, opcional) ,
    "xOffset": (int positive),
    "yOffset": (int positive),
    "watermarkRotation": (int between 0 and 360)
}
